FROM php:8.5-fpm
RUN apt-get update && apt-get install -y libpq-dev zip unzip git \
    && docker-php-ext-install pdo pdo_pgsql \
    && pecl install redis && docker-php-ext-enable redis
COPY --from=composer:2.8 /usr/bin/composer /usr/bin/composer
WORKDIR /var/www/api
COPY . .
RUN composer install --no-dev --optimize-autoloader
